modLoader="javafml"
loaderVersion="[52,)"
license="All Rights Reserved"

[[mods]]
modId="flashstake"
version="1.1.5"
displayName="FlashStake"
authors="flashlight and luis"
description='''Апгрейд предметов, маркет, кейсы и дабл — экономика для сервера.'''

[[dependencies.flashstake]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.flashstake]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.21.2)"
    ordering="NONE"
    side="BOTH"
