modLoader = "javafml"
loaderVersion = "[49,)"
license = "All Rights Reserved"

[[mods]]
modId = "flashstake"
version="1.1.9"
displayName = "FlashStake"
authors = "flashlight and luis"
description = '''РђРїРіСЂРµР№Рґ РїСЂРµРґРјРµС‚РѕРІ, РјР°СЂРєРµС‚, РєРµР№СЃС‹ Рё РґР°Р±Р» вЂ” СЌРєРѕРЅРѕРјРёРєР° РґР»СЏ СЃРµСЂРІРµСЂР°.'''

[[dependencies.flashstake]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flashstake]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,1.20.5)"
ordering = "NONE"
side = "BOTH"
